### ISSUE TITLE
Read and write from radio TX/RX buffers

### ISSUE THREAD

**Issue by liquiddandruff** [SFUSatClub/obc-firmware#4] opened 2017-05-26 01:54 UTC

**Comment by selh** [comment] 2017-06-09 02:07
From discussion:
---
case 1: flipped bit caused by radiation/etc
solution: resend 

#### //TODO:
case 2: Latch up
solution: restart hardware

**Comment by richarthurs** [comment] 2018-07-22 06:44
Can we close this? @liquiddandruff

**Closed** 2018-07-22 19:35 UTC
Labels: Radio
